### ISSUE TITLE
Fix typo in readme

### ISSUE THREAD

**Issue by brunoanken** [davikawasaki/merge-split-pdf-react-app#2]
In the Readme's first section there's a little typo. The word `serveless` should be `serverless`.

**Comment by davikawasaki** [comment]
Fixed in [last commit](https://github.com/davikawasaki/merge-split-pdf-react-app/commit/326a6982179eb227467771cc4fe9f709d5a390fa).

**Comment by brunoanken** [comment]
minha primeira issue resolvida no GitHub, me sinto o Open-Source Lord.
